spring.jpa.hibernate.ddl-auto: create
spring.datasource.url: jdbc:mysql://localhost:3306/TemplateDb
spring.datasource.username: root
spring.datasource.password: Aa123456

spring:
  datasource:
    url: jdbc:h2:./test
    username: sa
    password : 
    driver-class-name: org.h2.Driver
    tomcat:
      max-wait: 10000
      max-active: 100
      max-idle: 20
      test-on-borrow: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
          
jsf:
  PROJECT_STAGE: Production
  FACELETS_LIBRARIES: /tags/tags.taglib.xml
  primefaces:
    theme: overcast
joinfaces:
  version: project.parent.version
spring-boot:
  version: project.parent.parent.parent.version
tomcat:
  version: tomcat.version
jetty:
  version: jetty.version
undertow:
  version: undertow.version
cdi:
  version: cdi.version
mojarra:
  version: mojarra.version
myfaces:
  version: myfaces.version
omnifaces:
  version: omnifaces1.version
angularfaces:
  version: angularfaces.version
primefaces:
  version: primefaces.version
primefaces-extensions:
  version: primefaces-extensions.version
bootsfaces:
  version: bootsfaces.version
butterfaces:
  version: butterfaces.version
richfaces:
  version: richfaces.version

        